import { readdir, readFile } from 'node:fs/promises'
import { join } from 'node:path'

const specPath = new URL('../../server/docs/openapi.json', import.meta.url)
const generatedDir = new URL('../src/api/generated/', import.meta.url)
const methods = new Set(['get', 'put', 'post', 'delete', 'patch', 'head', 'options', 'trace'])

const spec = JSON.parse(await readFile(specPath, 'utf8'))
const seen = new Map()
for (const [path, item] of Object.entries(spec.paths ?? {})) {
  for (const [method, operation] of Object.entries(item ?? {})) {
    if (!methods.has(method)) continue
    const id = operation?.operationId
    if (!id) throw new Error(`${method.toUpperCase()} ${path} missing operationId`)
    const previous = seen.get(id)
    if (previous) throw new Error(`duplicate operationId ${id}: ${previous} and ${method.toUpperCase()} ${path}`)
    seen.set(id, `${method.toUpperCase()} ${path}`)
  }
}

for (const file of await generatedFiles(generatedDir)) {
  const body = await readFile(file, 'utf8')
  if (!body.startsWith('// This file is auto-generated by @hey-api/openapi-ts')) {
    throw new Error(`${file} is inside src/api/generated but missing generated header`)
  }
}

async function generatedFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const path = join(dir.pathname, entry.name)
    if (entry.isDirectory()) files.push(...await generatedFiles(new URL(`${entry.name}/`, dir)))
    else if (entry.name.endsWith('.ts')) files.push(path)
  }
  return files
}

console.log(`OpenAPI ok: ${seen.size} operations, generated client is marked read-only.`)
