/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUsersRouteImport } from './routes/_auth.users'
import { Route as AuthSessionsRouteImport } from './routes/_auth.sessions'
import { Route as AuthRolesRouteImport } from './routes/_auth.roles'
import { Route as AuthOperationLogsRouteImport } from './routes/_auth.operation-logs'
import { Route as AuthMenusRouteImport } from './routes/_auth.menus'
import { Route as AuthLoginLogsRouteImport } from './routes/_auth.login-logs'
import { Route as AuthForbiddenRouteImport } from './routes/_auth.forbidden'
import { Route as AuthDictionariesRouteImport } from './routes/_auth.dictionaries'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthApisRouteImport } from './routes/_auth.apis'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsRoute = AuthSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOperationLogsRoute = AuthOperationLogsRouteImport.update({
  id: '/operation-logs',
  path: '/operation-logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMenusRoute = AuthMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginLogsRoute = AuthLoginLogsRouteImport.update({
  id: '/login-logs',
  path: '/login-logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForbiddenRoute = AuthForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictionariesRoute = AuthDictionariesRouteImport.update({
  id: '/dictionaries',
  path: '/dictionaries',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApisRoute = AuthApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apis': typeof AuthApisRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dictionaries': typeof AuthDictionariesRoute
  '/forbidden': typeof AuthForbiddenRoute
  '/login-logs': typeof AuthLoginLogsRoute
  '/menus': typeof AuthMenusRoute
  '/operation-logs': typeof AuthOperationLogsRoute
  '/roles': typeof AuthRolesRoute
  '/sessions': typeof AuthSessionsRoute
  '/users': typeof AuthUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apis': typeof AuthApisRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dictionaries': typeof AuthDictionariesRoute
  '/forbidden': typeof AuthForbiddenRoute
  '/login-logs': typeof AuthLoginLogsRoute
  '/menus': typeof AuthMenusRoute
  '/operation-logs': typeof AuthOperationLogsRoute
  '/roles': typeof AuthRolesRoute
  '/sessions': typeof AuthSessionsRoute
  '/users': typeof AuthUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/apis': typeof AuthApisRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/dictionaries': typeof AuthDictionariesRoute
  '/_auth/forbidden': typeof AuthForbiddenRoute
  '/_auth/login-logs': typeof AuthLoginLogsRoute
  '/_auth/menus': typeof AuthMenusRoute
  '/_auth/operation-logs': typeof AuthOperationLogsRoute
  '/_auth/roles': typeof AuthRolesRoute
  '/_auth/sessions': typeof AuthSessionsRoute
  '/_auth/users': typeof AuthUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/apis'
    | '/dashboard'
    | '/dictionaries'
    | '/forbidden'
    | '/login-logs'
    | '/menus'
    | '/operation-logs'
    | '/roles'
    | '/sessions'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/apis'
    | '/dashboard'
    | '/dictionaries'
    | '/forbidden'
    | '/login-logs'
    | '/menus'
    | '/operation-logs'
    | '/roles'
    | '/sessions'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/apis'
    | '/_auth/dashboard'
    | '/_auth/dictionaries'
    | '/_auth/forbidden'
    | '/_auth/login-logs'
    | '/_auth/menus'
    | '/_auth/operation-logs'
    | '/_auth/roles'
    | '/_auth/sessions'
    | '/_auth/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions': {
      id: '/_auth/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthSessionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles': {
      id: '/_auth/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/operation-logs': {
      id: '/_auth/operation-logs'
      path: '/operation-logs'
      fullPath: '/operation-logs'
      preLoaderRoute: typeof AuthOperationLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/menus': {
      id: '/_auth/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AuthMenusRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login-logs': {
      id: '/_auth/login-logs'
      path: '/login-logs'
      fullPath: '/login-logs'
      preLoaderRoute: typeof AuthLoginLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forbidden': {
      id: '/_auth/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthForbiddenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictionaries': {
      id: '/_auth/dictionaries'
      path: '/dictionaries'
      fullPath: '/dictionaries'
      preLoaderRoute: typeof AuthDictionariesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/apis': {
      id: '/_auth/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof AuthApisRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthApisRoute: typeof AuthApisRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDictionariesRoute: typeof AuthDictionariesRoute
  AuthForbiddenRoute: typeof AuthForbiddenRoute
  AuthLoginLogsRoute: typeof AuthLoginLogsRoute
  AuthMenusRoute: typeof AuthMenusRoute
  AuthOperationLogsRoute: typeof AuthOperationLogsRoute
  AuthRolesRoute: typeof AuthRolesRoute
  AuthSessionsRoute: typeof AuthSessionsRoute
  AuthUsersRoute: typeof AuthUsersRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthApisRoute: AuthApisRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDictionariesRoute: AuthDictionariesRoute,
  AuthForbiddenRoute: AuthForbiddenRoute,
  AuthLoginLogsRoute: AuthLoginLogsRoute,
  AuthMenusRoute: AuthMenusRoute,
  AuthOperationLogsRoute: AuthOperationLogsRoute,
  AuthRolesRoute: AuthRolesRoute,
  AuthSessionsRoute: AuthSessionsRoute,
  AuthUsersRoute: AuthUsersRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
